### ISSUE TITLE
Dark theme is on but not Activating?

### ISSUE THREAD

**Issue by Dashon1** [flathub/info.febvre.Komikku#34]
I installed komikku through the flatpak on flathub. For some reason toggling the dark theme button doesn't do anything. Currently on openSuse Tumbleweed.

**Comment by valos** [comment]
A possibly solution https://gitlab.com/valos/Komikku/-/issues/26

**Comment by Dashon1** [comment]
Ok thanks for the update.

**Comment by doidge-kyle** [comment]
I wanted to add onto this because I have just installed and am experiencing the same thing and the other linked thread doesn't seem to help.

Maybe this is my ignorance with Linux, but I have installed multiple themes with multiple GTK version supports and nothing has changed. I see my themes are installed at /usr/share/themes and I see that some of the themes that I tested have a gtk folder in there.

I saw that another location that themes may be located in is ~/.themes but I do not see any there. I have tested restarting the app after applying new themes, even so far as installing a Cinnamon applet to enable Dark Mode to ensure I am hopefully not missing something.

Would love to get a dark theme enabled on this!

**Comment by valos** [comment]
Ok, thanks. Certainly interesting for others.

Unfortunately, this is not the right place to make an issue. This is not the Komikku repo. It's just a repo allowing the construction of Flatpak packages of Komikku.

The correct place is https://gitlab.com/valos/Komikku/-/issues

**Comment by doidge-kyle** [comment]
Apologies! Got directed here from a search but appreciate pointing me in the right direction.
